In [344]:
import torch.nn as nn
import torch.optim as optim

In [345]:
import torch

In [346]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(10,5)
        self.fc2 = nn.Linear(5,3)
        self.fc3 = nn.Linear(3,2)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    

In [347]:
model = NeuralNetwork()
model

NeuralNetwork(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=3, bias=True)
  (fc3): Linear(in_features=3, out_features=2, bias=True)
  (relu): ReLU()
)

In [348]:
criterion = nn.CrossEntropyLoss()
criterion

CrossEntropyLoss()

In [349]:
optimizer = optim.SGD(model.parameters(), lr=0.8)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.8
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [350]:
input_data = torch.randn(100,10)
target_data = torch.randint(0,2, (100,))
input_data
target_data

tensor([0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0])

In [351]:
output = model(input_data)
output

tensor([[-0.2446,  0.2667],
        [-0.3562,  0.3349],
        [-0.3205,  0.2834],
        [-0.2086,  0.2320],
        [-0.3644,  0.3374],
        [-0.4499,  0.4717],
        [-0.2990,  0.2860],
        [-0.2762,  0.2686],
        [-0.2103,  0.2584],
        [-0.3072,  0.2772],
        [-0.2368,  0.2768],
        [-0.2888,  0.3055],
        [-0.2090,  0.2314],
        [-0.5978,  0.6814],
        [-0.2293,  0.2483],
        [-0.3236,  0.2927],
        [-0.2117,  0.2326],
        [-0.2895,  0.2689],
        [-0.3929,  0.3493],
        [-0.2113,  0.2324],
        [-0.3564,  0.3292],
        [-0.2547,  0.2537],
        [-0.3409,  0.3433],
        [-0.2881,  0.2961],
        [-0.1537,  0.2056],
        [-0.3596,  0.3847],
        [-0.3114,  0.2799],
        [-0.4424,  0.5092],
        [-0.2658,  0.2579],
        [-0.4555,  0.4931],
        [-0.2936,  0.3286],
        [-0.2604,  0.2553],
        [-0.2019,  0.2281],
        [-0.3829,  0.3895],
        [-0.2813,  0.2651],
        [-0.0823,  0

In [352]:
epoch_num = 3000

In [353]:
for epoch in range(epoch_num):
    optimizer.zero_grad()
    output = model(input_data)
    loss = criterion(output, target_data)
    loss.backward()
    optimizer.step()
    if epoch == 0:
        print(f'Epoch {epoch+1}/{epoch_num}, Loss: {loss.item()}')
    if (epoch+1) % 50 == 0:
        print(f'Epoch {epoch+1}/{epoch_num}, Loss: {loss.item()}')

Epoch 1/3000, Loss: 0.7340689301490784
Epoch 50/3000, Loss: 0.4466016888618469
Epoch 100/3000, Loss: 0.29062724113464355
Epoch 150/3000, Loss: 0.3115476667881012
Epoch 200/3000, Loss: 0.16098140180110931
Epoch 250/3000, Loss: 0.1241152212023735
Epoch 300/3000, Loss: 0.11535228788852692
Epoch 350/3000, Loss: 0.10430190712213516
Epoch 400/3000, Loss: 0.09893843531608582
Epoch 450/3000, Loss: 0.09706688672304153
Epoch 500/3000, Loss: 0.09517750889062881
Epoch 550/3000, Loss: 3.0582170486450195
Epoch 600/3000, Loss: 0.4124358892440796
Epoch 650/3000, Loss: 0.373855859041214
Epoch 700/3000, Loss: 0.36932170391082764
Epoch 750/3000, Loss: 0.3623121976852417
Epoch 800/3000, Loss: 0.3453260362148285
Epoch 850/3000, Loss: 0.3338314890861511
Epoch 900/3000, Loss: 0.32872405648231506
Epoch 950/3000, Loss: 0.33864104747772217
Epoch 1000/3000, Loss: 0.3120214343070984
Epoch 1050/3000, Loss: 0.2809996008872986
Epoch 1100/3000, Loss: 0.34741145372390747
Epoch 1150/3000, Loss: 0.24045982956886292
Epoc

In [354]:
print("Updated model parameters:")
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Updated model parameters:
fc1.weight tensor([[ 1.5638,  2.1949,  0.5602,  0.6434, -0.6401,  0.8657, -0.8501,  0.6179,
         -0.3506,  0.9480],
        [ 1.8225,  1.0024, -1.0423, -0.7242, -1.0920,  2.0651, -2.4504, -0.0032,
          0.0545,  1.5198],
        [ 1.1562, -1.5326,  2.0466,  0.1883,  0.0353, -0.4486, -0.6247,  0.2720,
         -0.2422, -2.1679],
        [ 1.1704, -1.0846,  1.3814,  1.8419,  0.1891,  1.2078, -0.7145, -0.1148,
         -0.1614,  0.1948],
        [ 0.3333, -0.6590,  1.2999,  0.9374, -1.4499, -0.3844, -0.9363, -0.8789,
         -1.5983, -0.8461]])
fc1.bias tensor([-0.6346, -2.0716, -0.4924, -1.7595,  0.8481])
fc2.weight tensor([[-2.7144,  1.4378, -3.1550, -0.8800,  1.9683],
        [ 0.2260, -3.4383, -0.8444,  1.9556,  0.6924],
        [ 1.5266, -2.4419, -1.0361, -0.9894, -2.1916]])
fc2.bias tensor([ 0.3888, -2.2141, -0.4271])
fc3.weight tensor([[-2.8070, -2.2924, -2.1017],
        [ 2.8684,  2.4338,  2.2542]])
fc3.bias tensor([ 1.2439, -1.3171])


In [355]:
print("loss:", loss.item())

loss: 0.22339877486228943


In [356]:
def calculate_accurary(output, target):
    _, predicted = torch.max(output, 1)
    print(predicted)
    correct_predicted = (predicted == target).sum().item()/target.size(0)
    print(f'Correctly Predicted: {correct_predicted:.6f}')
    return correct_predicted

In [357]:
accuracy = calculate_accurary(output, target_data)
print(f'Accuracy:{accuracy * 100}%')

tensor([0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0])
Correctly Predicted: 0.900000
Accuracy:90.0%
