In [5]:
import torch

In [6]:
torch.cuda.is_available()

True

In [7]:
torch.cuda.current_device()

0

In [8]:
torch.cuda.device_count()

1

In [9]:
torch.cuda.memory_cached()

c:\Users\Nicol\anaconda3\Lib\site-packages\torch\cuda\memory.py:444: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(


0

In [10]:
cuda = torch.device('cuda')
cuda

device(type='cuda')

In [11]:
x = torch.tensor([10,20])
x

tensor([10, 20])

In [12]:
x_cuda = torch.tensor([11,22], device=cuda)
x_cuda

tensor([11, 22], device='cuda:0')

In [14]:
cuda1 = torch.device('cuda:1')
x_cuda1 = torch.tensor([11,22], device=cuda1)
x_cuda1

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [15]:
y = x.cuda()
y

tensor([10, 20], device='cuda:0')

In [16]:
torch.cuda.memory_allocated()

1024